Things have been going full steam ahead for the past two weeks.  Aerial Fabric classes are progressing nicely and I'm learning to do some easy tricks.  There's a low student/teacher ratio so I'm getting a lot of attention and time on the fabric.  The last open workout I worked a lot on my "Christ Hang" and "Crucifix" poses as well as the egg beater wrap.

Two Fridays ago The Afronauts played the Laughing Goat Coffeehouse again.  We had two new guest percussionists each play a set with us.  Overall it was a fun gig and we were pretty well-rehearsed going into it. We played a new song "Addis Black Widow" for the first time and although it veered and lurched, it never came completely off the rails.

Two Saturdays ago was the [March Fourth Marching Band](http://marchfourthmarchingband.com/) show at the Gothic in Englewood.  Logan and Brenda came with me.  It was an absolute blast.  Folks were hanging out along the bars on the street in costume and having a good time.  M4 was fantastic as usual.  If I thought I had a shot at joining that band, I'd seriously consider moving to Portland.  They are wicked fun. Their dance/stilt/acrobatics component has gotten a lot stronger this year as well.  I think the Gothic is my favorite venue in the Denver metro area.  It has a great mix of good sized open dance floor, several tiers of table seating, spacious balconies, and a second upstairs bar.  It's usually not filled to capacity and is overall pleasant.  We danced around a bit and asked Logan questions about the details of their equipment.  As soon as we arrived he went and walked across the front row, undoubtedly noting the make and model of every amplifier, effects pedal, or misc piece of audio gear.  When the bass player moved toward the front of the stage at one point, Logan noted that he was using flat-wound strings.  He's an encyclopedia of music trivia.  Definitely a fun night.

This past weekend has been jam-packed.  Friday I worked until around 6pm and then headed to Trident Cafe for Corey's photo exhibit opening.  Then I met up with Brenda for dinner at Trattoria on Pearl.  I headed home pretty exhausted from a packed week around 9:00pm.  But this was only a brief pause.  I rested for 30 minutes and then got dressed to head into Denver for a [Fantastic Hosts](https://www.facebook.com/FantasticHosts) dance party.  The theme was "Forbidden Planet" (outer space) so I wore my 70s zip-front one-piece jumpsuit which works well enough as a space uniform of some sort.  Spike up the mohawk and call it a costume.  So out the door I went.  I arrived around 11pm I think.  The venue was good with 3 separate rooms for deejays.  The main room upstairs which was always so crowded you couldn't dance and then two different basement rooms which were much less crowded.  Everyone was fully decked out in great costumes.  I ran into most of the folks I've met at Aerial Fabric so far and had fun chatting with them a bit.  [Here's a photo](https://www.facebook.com/media/set/?set=a.10150337926080216.338575.205573395215&type=3) from the event.  The Pan on stilts and the women in red with black wings are aerialists from my studio.  I danced and wondered around until quarter to 2 and was in bed by 2:30am.

But not long there.  Up again at 6:30 am to dress for a road trip down to Manitou Springs with Brenda for the [Emma Crawford Coffin Races](http://community.manitousprings.org/events/17th-annual-emma-crawford)  which is their odd mountain town festival analogous to Nederland's Frozen Dead Guy Days.  We stopped at our local Lamar's donut shop for some sugary road fuel and then made awesome time down to Colorado Springs.  Brenda showed me around her old town and we drove by the house she owns there.  Then we headed to Manitou and visited her friends Lorien and Nigel.  They have a gorgeous home there that they have been beautifully remodeling (that's polite conversation for "totally pimping out") over the past four years.  It's decked out with lots of windows, a huge billiards room, several large decks, outdoor hot tub, conservatory, spiral stairs to the master suite, etc.  We had mimosas and fresh fruit.  We were joined by another couple and then walked a couple of miles in to town for the coffin races.  We missed the parade, which was a shame, but we did catch all of the races.

<object width="400" height="300"> <param name="flashvars" value="offsite=true&lang=en-us&page_show_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157628015986762%2Fshow%2F&page_show_back_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157628015986762%2F&set_id=72157628015986762&jump_to="></param> <param name="movie" value="http://www.flickr.com/apps/slideshow/show.swf?v=109615"></param> <param name="allowFullScreen" value="true"></param><embed type="application/x-shockwave-flash" src="http://www.flickr.com/apps/slideshow/show.swf?v=109615" allowFullScreen="true" flashvars="offsite=true&lang=en-us&page_show_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157628015986762%2Fshow%2F&page_show_back_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157628015986762%2F&set_id=72157628015986762&jump_to=" width="400" height="300"></embed></object>


After the races we had fun in the arcade playing some old dime arcade games.  Brenda trounced me in Pac-man, which was humiliating, but I redeemed myself with Ms. Pac-man.  Then we grabbed a quick snack before meeting up again with the crew at a wine bar.  Brenda ordered a fancy pumkin drink with whipped cream.  After a little chatting it was time to walk back to the house.  I had to be back in Boulder for Uncle Bill's birthday dinner at [The Kitchen](http://thekitchencafe.com/index.shtml).  I had my occasional hankering for beef the past few weeks so I ordered the Colorado skirt steak.  It was pretty tasty but honestly the fries and homemade ketchup seemed even better.  After that I went back to Louisville and hung out with Brenda some more, working up our Guitar Hero game.

Today I got a late start and grabbed a breakfast quesadilla at Paul's Coffee.  It was good, but the goddamn teenage counter staff (again) couldn't seem to hold down the complexities of the "1. order 2. pay 3. actually give customer the food" sequence.  I ran some quick errands then drove up to Longmont for a Halloween jam party at Matt's farm.  It was the Stedfast group of punk rock teenagers and the Turtle Dove group of 30-something rock wannabes, and our respective cohorts.  It was a gorgeous warm day.  Stedfast played a set of their hilarious punk rock covers, including the shortest song I've ever heard (approx 13 seconds).  The Byron and Logan did some of their mostly-original drums/bass jammies under the name "Gort vs Goom".  Then Turtle Dove played our set.  Here are some photos and videos.

<object width="400" height="300"> <param name="flashvars" value="offsite=true&lang=en-us&page_show_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157627891409843%2Fshow%2F&page_show_back_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157627891409843%2F&set_id=72157627891409843&jump_to="></param> <param name="movie" value="http://www.flickr.com/apps/slideshow/show.swf?v=109615"></param> <param name="allowFullScreen" value="true"></param><embed type="application/x-shockwave-flash" src="http://www.flickr.com/apps/slideshow/show.swf?v=109615" allowFullScreen="true" flashvars="offsite=true&lang=en-us&page_show_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157627891409843%2Fshow%2F&page_show_back_url=%2Fphotos%2F88096431%40N00%2Fsets%2F72157627891409843%2F&set_id=72157627891409843&jump_to=" width="400" height="300"></embed></object>

<iframe width="420" height="315" src="http://www.youtube.com/embed/rEfGImX5iWI" frameborder="0" allowfullscreen></iframe>

<iframe width="420" height="315" src="http://www.youtube.com/embed/icPDULPqEqU" frameborder="0" allowfullscreen></iframe>

<iframe width="420" height="315" src="http://www.youtube.com/embed/CQ3FnJC2gi8" frameborder="0" allowfullscreen></iframe>

A small bit of technical note: I've started using [Flickr](http://flickr.com) to manage my photos.  My home-grown photo management system has served me well for the past decade, but I've grown tired of maintaining it and futzing too much with EXIF metadata and JSON files, so up to Flickr it goes.

Man, I'm pretty beat now though.  I need to start penciling in some down time after work Friday before diving in to weekend mode.
